title:   Aarti Srinivasan
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  <br><br><br>
  Highly analytical business intelligence engineer with a proven ability to build analytical tools, develop insightful models around customer experience and performance, and drive process efficiency and automation. Skilled at working with key stakeholders to drive the adoption of analytical tools across the business. Proficient in SQL, Excel, Tableau, and Python. Proven success working on cross-functional teams 
  to champion and drive multiple projects.<br><br><br>
  <a href="https://www.linkedin.com/in/aartisrinivasan/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/profile/aarti4429">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/aartisrinivasan/Portfolio-Aarti-Srinivasan-64c565db984046238e163f63fd4a3bc7">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   

 
